### ISSUE TITLE
When taped on date its returning calendar instead of date.

### ISSUE THREAD

**Issue by shashankreddy509** [niravspaceo/NVCalendar#1]
I pressed on a date and the app crashes, then i found out that "tap.view.tag" is returning a calendar instead of date. in lblDateTapped method.

this is the point where i am getting the error

selectedLbl = (UILabel *)[self viewWithTag:tap.view.tag];
but this "selectedLbl" is returning calendar instead of date.

dateLbl.text  = selectedLbl.text;

The exception is as follows.
Exception is :- -[NVCalendar text]: unrecognized selector sent to instance 0x7f96e8d65dd0

so could you help regarding this.
its very urgent for me.

Thanks in advance

**Comment by niravspaceo** [comment]
I didn't find any label named "selectedLbl", and I am able to run the code without crash. I also checked the tap method on UILabel. But everything works fine.

Did you change my code ?

Please let me know so I can help you out.

Regards
